"use client";

import { useEffect, useState } from "react";

const brands = [
  ["Apple", "logo_iphone_ngang_eac93ff477.webp"], ["Samsung", "logo_samsung_ngang_1624d75bd8.webp"],
  ["Xiaomi", "logo_xiaomi_ngang_0faf267234.webp"], ["OPPO", "logo_oppo_ngang_68d31fcd73.webp"],
  ["vivo", "logo_vivo_ngang_45494ff733.webp"], ["realme", "logo_realme_ngang_0185815a13.webp"], ["HONOR", "logo_honor_ngang_814fca59e4.webp"],
];
const products = [
  ["iPhone 17 Pro Max", "34.990.000đ", "37.990.000đ", "-8%"], ["Samsung Galaxy S26 Ultra", "29.490.000đ", "32.990.000đ", "HOT"],
  ["Xiaomi 15 Ultra", "21.990.000đ", "24.990.000đ", "-12%"], ["OPPO Find X9 Pro", "19.990.000đ", "22.490.000đ", "-11%"], ["vivo X200 Pro", "18.490.000đ", "20.990.000đ", "MỚI"],
];
const slides = ["/assets/videos/applv1.mp4", "/assets/videos/sams.mp4", "/assets/videos/xiao.mp4", "/assets/videos/ooppv1.mp4"];

export default function Home() {
  const [slide, setSlide] = useState(0); const [tab, setTab] = useState("GỢI Ý"); const [menuOpen, setMenuOpen] = useState(false); const [search, setSearch] = useState(""); const [subscribed, setSubscribed] = useState(false);
  useEffect(() => { const timer = window.setInterval(() => setSlide((current) => (current + 1) % slides.length), 6000); return () => window.clearInterval(timer); }, []);
  const moveSlide = (direction: number) => setSlide((current) => (current + direction + slides.length) % slides.length);
  return <div className="shop-shell">
    <header className="site-header"><div className="header-inner"><button className="mobile-menu-button" onClick={() => setMenuOpen(true)} aria-label="Mở menu">☰</button><a className="brand-mark" href="#top"><img src="/assets/logos/sean.gif" alt="QHUN22 Mobile" /></a><form className="search-box" onSubmit={(event) => event.preventDefault()}><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Nhập sản phẩm mà bạn muốn tìm..." /><button aria-label="Tìm kiếm">⌕</button></form><nav className="header-actions" aria-label="Tài khoản"><a href="#wishlist"><span>♡</span><small>Yêu thích</small></a><a href="#cart"><span>🛒</span><small>Giỏ hàng</small></a><a href="#orders"><span>▤</span><small>Tra cứu đơn</small></a><a href="#login"><span>◯</span><small>Đăng nhập</small></a></nav><button className="mobile-search-button" aria-label="Tìm kiếm">⌕</button></div></header>
    {menuOpen && <div className="drawer-backdrop" onClick={() => setMenuOpen(false)}><aside className="mobile-drawer" onClick={(event) => event.stopPropagation()}><button onClick={() => setMenuOpen(false)}>×</button><img src="/assets/logos/sean.gif" alt="QHUN22" /><p>Xin chào, Khách</p>{["Trang chủ", "Yêu thích", "Giỏ hàng", "Tra cứu đơn", "Đăng nhập"].map((item) => <a href="#top" key={item}>{item}</a>)}</aside></div>}
    <main id="top"><section className="hero-slider"><video key={slides[slide]} autoPlay muted loop playsInline className="hero-video"><source src={slides[slide]} type="video/mp4" /></video><div className="hero-shade"><p>QHUN22 MOBILE</p><h1>Công nghệ trong tầm tay</h1><span>Chính hãng · Giá tốt · Giao hàng toàn quốc</span></div><button className="slider-arrow left" onClick={() => moveSlide(-1)} aria-label="Slide trước">‹</button><button className="slider-arrow right" onClick={() => moveSlide(1)} aria-label="Slide sau">›</button><div className="slider-dots">{slides.map((_, index) => <button className={index === slide ? "active" : ""} onClick={() => setSlide(index)} key={index} aria-label={`Slide ${index + 1}`} />)}</div></section>
      <section className="promo-strip"><div><strong>Miễn phí vận chuyển</strong><span>Cho đơn từ 500.000đ</span></div><div><strong>Đổi trả dễ dàng</strong><span>Trong vòng 30 ngày</span></div><div><strong>Thanh toán an toàn</strong><span>Bảo mật tuyệt đối</span></div><div><strong>Tư vấn tận tâm</strong><span>Hotline 032.722.1005</span></div></section>
      <section className="content-section brands-section"><div className="section-heading"><span>THƯƠNG HIỆU</span><h2>Hãng nổi bật</h2><a href="#products">Xem tất cả →</a></div><div className="brand-row">{brands.map(([name, logo]) => <a href="#products" className="brand-tile" key={name}><img src={`/assets/icons/${logo}`} alt={name} /></a>)}</div></section>
      <section className="hot-sale"><div className="hot-sale-head"><div><span className="eyebrow">ƯU ĐÃI MỖI NGÀY</span><h2>Hot sale <em>chớp nhoáng</em></h2></div><div className="countdown"><small>KẾT THÚC SAU</small><b>08</b><i>:</i><b>16</b><i>:</i><b>42</b></div></div><div className="tab-row">{["GỢI Ý", "BÁN CHẠY", "HOTSALE"].map((item) => <button className={tab === item ? "selected" : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</div><div className="product-grid" id="products">{products.map(([name, price, old, tag]) => <a href="#product" className="product-card" key={name}><div className="product-image"><span>{tag}</span><div className="image-placeholder">{name.split(" ")[0]}</div><button aria-label="Thêm yêu thích" onClick={(event) => event.preventDefault()}>♡</button></div><div className="product-details"><h3>{name}</h3><strong>{price}</strong><del>{old}</del><div className="stars">★★★★★ <small>Đã bán 24</small></div></div></a>)}</div><button className="outline-button">Xem thêm sản phẩm <span>→</span></button></section>
      <section className="newsletter"><div><span className="eyebrow">Ở LẠI CÙNG QHUN22</span><h2>Nhận tư vấn và ưu đãi</h2><p>Đăng ký để không bỏ lỡ những sản phẩm mới và chương trình hấp dẫn.</p></div>{subscribed ? <strong className="subscribed">Cảm ơn bạn đã đăng ký!</strong> : <form onSubmit={(event) => { event.preventDefault(); setSubscribed(true); }}><input type="text" required placeholder="Email hoặc số điện thoại" /><button>ĐĂNG KÝ NGAY →</button></form>}</section></main>
    <footer className="site-footer"><div className="footer-top"><div><img src="/assets/logos/sean.gif" alt="QHUN22 Mobile" /><p>Điện thoại chính hãng, trải nghiệm an tâm.</p></div><div><h3>QHUN22</h3><a href="#top">Trang chủ</a><a href="#products">Sản phẩm</a><a href="#orders">Tra cứu đơn hàng</a></div><div><h3>Chính sách</h3><a href="#policy">Đổi trả & bảo hành</a><a href="#policy">Giao hàng</a><a href="#policy">Bảo mật</a></div><div><h3>Liên hệ</h3><a href="tel:0327221005">032.722.1005</a><a href="mailto:qhun22@gmail.com">qhun22@gmail.com</a><span>Hà Nội, Việt Nam</span></div></div><div className="footer-bottom">© 2026 QHUN22 MOBILE <span>Thiết kế cho trải nghiệm mua sắm tốt hơn.</span></div></footer><div className="floating-contact"><a href="tel:0327221005">☎</a><a href="https://zalo.me/0327221005">Z</a><a href="#top">↑</a></div>
  </div>;
}
